version: '3.2'
services:
  nginx:
    build:
      context: ../
      dockerfile: membership-portal-ui/dev.Dockerfile
    volumes:
      - ../:/var/www
      - /var/www/membership-portal-ui/node_modules
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=
      - GOOGLE_AUTH_DOMAIN=
      - GOOGLE_CLIENT_ID=913307270840-751ad0psdu1q2a7m81np30g062osgpp5.apps.googleusercontent.com