export default {
  API_URL: process.env.WEBPACK ? "http://localhost:8080/app" : "/app",
  CLIENT_ROOT_URL: "",
  google: {
    apiKey: process.env.GOOGLE_API_KEY,
    authDomain: process.env.GOOGLE_AUTH_DOMAIN,
    clientId: "913307270840-751ad0psdu1q2a7m81np30g062osgpp5.apps.googleusercontent.com",
    hostedDomain: "g.ucla.edu",
  },
  routes: {
    user: {
      user: "/api/v1/user",
      activity: "/api/v1/user/activity",
      admins: "/api/v1/user/admins",
    },
    activity: "/api/v1/activity",
    auth: {
      register: "/api/v1/register",
      login: "/api/v1/auth/login",
      oneclick: "/api/v1/one-click",
    },
    events: {
      event: "/api/v1/event",
      past: "/api/v1/event/past",
      future: "/api/v1/event/future",
    },
    attendance: {
      fetch: "/api/v1/attendance",
      attend: "/api/v1/attendance/attend",
    },
    rsvp: {
      get: "/api/v1/rsvp",
      create: "/api/v1/rsvp/add",
      cancel: "/api/v1/rsvp",
    },
    leaderboard: "/api/v1/leaderboard",
    admin: {
      promote: "/api/v1/admin/promote",
    },
    image: {
      upload: "/api/v1/image",
      specific: "/api/v1/image/raw",
      all: "/api/v1/image",
    },
  },
  organization: {
    logo: "/logo.png",
    logoLight: "/logo-white.png",
    loginTileBackground: "/login-tile-bg.jpg",
    shortName: "ACM chapter at UCLA",
    name: "Association for Computing Machinery chapter at UCLA",
    mission:
      "To create and support an inclusive community for all of those interested in computer science at UCLA and cultivate the next generation of technology leaders by fostering the spirit of innovation, a culture of creativity, and promoting equity, diversity, and inclusion within tech.",
    officers: [
      {
        name: "Ava Asmani",
        position: "President",
        picture: "/officers/AvaAsmani.jpg",
      },
      {
        name: "Zack Pakin",
        position: "External Vice President",
        picture: "/officers/ZackPakin.jpg",
      },
      {
        name: "Sujay Jain",
        position: "Internal Vice President",
        picture: "/officers/SujayJain.jpg",
      },
      {
        name: "Christina Tong",
        position: "Co-President, Hack",
        picture: "/officers/ChristinaTong.jpg",
      },
      {
        name: "Nareh Agazaryan",
        position: "Co-President, Hack",
        picture: "/officers/NarehAgazaryan.jpg",
      },
      {
        name: "Aman Oberoi",
        position: "President, AI",
        picture: "/officers/AmanOberoi.jpg",
      },
      {
        name: "Paige Brown",
        position: "Co-President, ACM-W",
        picture: "/officers/PaigeBrown.jpg",
      },
      {
        name: "Ethan Wong",
        position: "Co-President, ACM-W",
        picture: "/officers/EthanWong.jpg",
      },
      {
        name: "Robert Lee",
        position: "President, ICPC",
        picture: "/officers/RobertLee.jpg",
      },
      {
        name: "Ray Hsiao",
        position: "Co-President, Game Studio",
        picture: "/officers/RayHsiao.jpg",
      },
      {
        name: "Caroline Wang",
        position: "Co-President, Game Studio",
        picture: "/officers/CarolineWang.jpg",
      },
      {
        name: "Jerry Xu",
        position: "Co-President, Cyber",
        picture: "/officers/JerryXu.jpg",
      },
      {
        name: "Stephen Kelman",
        position: "Co-President, Cyber",
        picture: "/officers/StephenKelman.jpg",
      },
      {
        name: "Milo Kearney",
        position: "General President, Teach LA",
        picture: "/officers/MiloKearney.jpg",
      },
      {
        name: "Eden Yu",
        position: "Vice President, Teach LA",
        picture: "/officers/EdenYu.jpg",
      },
      {
        name: "Jiin Kim",
        position: "Dev President, Teach LA",
        picture: "/officers/JiinKim.jpg",
      },
      {
        name: "Muthu Palaniappan",
        position: "Co-President, Design",
        picture: "/officers/MuthuPalaniappan.jpg",
      },
      {
        name: "Amy Seo",
        position: "Co-President, Design",
        picture: "/officers/AmySeo.png",
      },
    ],
    resources: [
      {
        type: "github",
        title: "Github",
        subtitle: "github.com/uclaacm",
        link: "https://github.com/uclaacm",
      },
      {
        type: "website",
        title: "Website",
        subtitle: "uclaacm.com",
        link: "https://www.uclaacm.com/",
      },
      {
        type: "discord",
        title: "Discord",
        subtitle: "bit.ly/ACMdiscord",
        link: "https://bit.ly/ACMdiscord",
      },
      {
        type: "facebook",
        title: "Facebook",
        subtitle: "facebook.com/uclaacm",
        link: "https://facebook.com/uclaacm",
      },
      {
        type: "medium",
        title: "Medium",
        subtitle: "tech@ucla",
        link: "https://medium.com/techatucla",
      },
    ],
  },
  levels: [
    { startsAt: 0, rank: "Hello, World!" },
    { startsAt: 20, rank: "Factorial Fly" },
    { startsAt: 40, rank: "Exponential Elephant" },
    { startsAt: 80, rank: "Cubic Chipmunk" },
    { startsAt: 120, rank: "Quadratic Quokka" },
    { startsAt: 180, rank: "Linearithmic Lizard" },
    { startsAt: 240, rank: "Linear Lemur" },
    { startsAt: 320, rank: "Square Root Sabre-Tooth" },
    { startsAt: 400, rank: "Logarithmic Lynx" },
    { startsAt: 500, rank: "Constant Cheetah" },
    { startsAt: 800, rank: "Extraterrestrial Eagle" },
    { startsAt: 1000, rank: "Binomial Baboon" },
    { startsAt: 1300, rank: "Scalar Scorpion" },
  ],
  // majors as of Fall 2023
  majors: [
    "Aerospace Engineering",
    "African American Studies",
    "African and Middle Eastern Studies",
    "American Indian Studies",
    "American Literature and Culture",
    "Ancient Near East and Egyptology",
    "Anthropology",
    "Arabic",
    "Architectural Studies",
    "Art",
    "Art History",
    "Asian American Studies",
    "Asian Humanities",
    "Asian Languages and Linguistics",
    "Asian Religions",
    "Asian Studies",
    "Astrophysics",
    "Atmospheric and Oceanic Sciences",
    "Atmospheric and Oceanic Sciences/Mathematics",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biophysics",
    "Business Economics",
    "Central and East European Languages and Cultures",
    "Chemical Engineering",
    "Chemistry",
    "Chemistry/Materials Science",
    "Chicana and Chicano Studies",
    "Chinese",
    "Civil Engineering",
    "Classical Civilization",
    "Climate Science",
    "Cognitive Science",
    "Communication",
    "Comparative Literature",
    "Computational and Systems Biology",
    "Computer Engineering",
    "Computer Science",
    "Computer Science and Engineering",
    "Dance",
    "Data Theory",
    "Design | Media Arts",
    "Disability Studies",
    "Earth and Environmental Science",
    "Ecology, Behavior, and Evolution",
    "Economics",
    "Education and Social Transformation",
    "Electrical Engineering",
    "English",
    "Environmental Science",
    "Ethnomusicology",
    "European Language and Transcultural Studies",
    "European Languages and Transcultural Studies with French and Francophone",
    "European Languages and Transcultural Studies with German",
    "European Languages and Transcultural Studies with Italian",
    "European Languages and Transcultural Studies with Scandinavian",
    "European Studies",
    "Film and Television",
    "Gender Studies",
    "Geography",
    "Geography/Environmental Studies",
    "Geology",
    "Geology/Engineering Geology",
    "Geophysics",
    "Global Jazz Studies",
    "Global Studies",
    "Greek",
    "Greek and Latin",
    "History",
    "Human Biology and Society",
    "Individual Field of Concentration",
    "Individual Field of Concentration in the Arts and Architecture",
    "Individual Field of Concentration in Theater, Film and Television",
    "International Development Studies",
    "Iranian Studies",
    "Japanese",
    "Jewish Studies",
    "Korean",
    "Labor Studies",
    "Latin",
    "Latin American Studies",
    "Linguistics",
    "Linguistics and Anthropology",
    "Linguistics and Asian Languages and Cultures",
    "Linguistics and Computer Science",
    "Linguistics and English",
    "Linguistics and Philosophy",
    "Linguistics and Psychology",
    "Linguistics and Spanish",
    "Linguistics, Applied",
    "Marine Biology",
    "Materials Engineering",
    "Mathematics",
    "Mathematics for Teaching",
    "Mathematics of Computation",
    "Mathematics, Applied",
    "Mathematics, Financial Actuarial",
    "Mathematics/Applied Science",
    "Mathematics/Economics",
    "Mechanical Engineering",
    "Microbiology, Immunology, and Molecular Genetics",
    "Middle Eastern Studies",
    "Molecular, Cell, and Developmental Biology",
    "Music Composition",
    "Music Education",
    "Music Industry",
    "Music Performance",
    "Musicology",
    "Neuroscience",
    "Nordic Studies",
    "Nursing",
    "Philosophy",
    "Physics",
    "Physiological Science",
    "Political Science",
    "Portuguese and Brazilian Studies",
    "Psychobiology",
    "Psychology",
    "Public Affairs",
    "Public Health",
    "Religion, Study of",
    "Russian Language and Literature",
    "Russian Studies",
    "Sociology",
    "Southeast Asian Studies",
    "Spanish",
    "Spanish and Community and Culture",
    "Spanish and Linguistics",
    "Spanish and Portuguese",
    "Statistics and Data Science",
    "Theater",
    "Undeclared Engineering and Applied Science",
    "Undeclared Humanities",
    "Undeclared Life Sciences",
    "Undeclared Physical Sciences",
    "Undeclared Social Sciences",
    "World Arts and Cultures",
  ],
  committees: ["AI", "Cyber", "Design", "Hack", "ICPC", "Studio", "TeachLA", "W", "Cloud"],
  committeeColors: [
    ["ACM", "#1d6bff"],
    ["AI", "#28b2fd"],
    ["Cyber", "#ffba43"],
    ["Design", "#fe833d"],
    ["Hack", "#c95ffd"],
    ["ICPC", "#ff6b6b"],
    ["Studio", "#ed3267"],
    ["TeachLA", "#5fda10"],
    ["W", "#01d4cb"],
    ["Cloud", "#9f97ff"],
  ],
};
