export default {
  API_URL: process.env.WEBPACK ? 'http://localhost:8080/app' : '/app',
  CLIENT_ROOT_URL: '',
  facebook: {
    appId: '1356860031017067',
  },
  routes: {
    user: {
      user: '/api/v1/user',
      activity: '/api/v1/user/activity',
    },
    activity: '/api/v1/activity',
    auth: {
      register: '/api/v1/auth/register',
      login: '/api/v1/auth/login',
      resetPassword: '/api/v1/auth/resetPassword',
    },
    events: {
      event: '/api/v1/event',
      past: '/api/v1/event/past',
      future: '/api/v1/event/future',
    },
    attendance: {
      fetch: '/api/v1/attendance',
      attend: '/api/v1/attendance/attend',
    },
    leaderboard: '/api/v1/leaderboard',
  },
  organization: {
    logo: '/assets/images/logo.png',
    logoLight: '/assets/images/logo-white.png',
    loginTileBackground: '/assets/images/login-tile-bg.jpg',
    shortName: 'UCLA ACM',
    name: 'UCLA Association for Computing Machinery',
    mission: 'To create and support an inclusive community for all of those interested in computer science at UCLA and cultivate the next generation of technology leaders by promoting the spirit of innovation, a culture of creativity, and aspiration of entrepreneurship.',
    officers: [
      {
        name: 'Rucha Patki',
        position: 'President',
        email: 'ruchapatki@gmail.com',
        picture: '/assets/images/officers/RuchaPatki.jpg',
      },
      {
        name: 'Katherine Chone',
        position: 'External VP',
        email: 'kchong612@gmail.com',
        picture: '/assets/images/officers/KatherineChong.jpg',
      },
      {
        name: 'William Chern',
        position: 'Internal VP',
        email: 'chern@ucla.edu',
        picture: '/assets/images/officers/WilliamChern.jpg',
      },
      {
        name: 'John Dang',
        position: 'President of AI',
        email: 'jamqd@ucla.edu',
        picture: '/assets/images/officers/JohnDang.jpg',
      },
      {
        name: 'Raji Jadhav',
        position: 'President of Hack',
        email: 'rajeshwari.jadhav6@gmail.com',
        picture: '/assets/images/officers/RajiJadhav.jpg',
      },
      {
        name: 'Elena Escalas',
        position: 'President of ICPC',
        email: 'elenaescalas@g.ucla.edu',
        picture: '/assets/images/officers/ElenaEscalas.jpg',
      },
      {
        name: 'Sanjana Sarda',
        position: 'President of Cyber',
        email: 'sanjanas.sardas@gmail.com',
        picture: '/assets/images/officers/SanjanaSarda.jpg',
      },
      {
        name: 'Kade Adams',
        position: 'Co-President of Game Studio',
        email: 'kadebadams@gmail.com',
        picture: '/assets/images/officers/KadeAdams.jpg',
      },
      {
        name: 'Evan Charfauros',
        position: 'Co-President of Game Studio',
        email: 'evancharfauros@gmail.com',
        picture: '/assets/images/officers/EvanCharfauros.jpg',
      },
      {
        name: 'Julia Baylon',
        position: 'President of ACM-W',
        email: 'juliabaylon01@gmail.com',
        picture: '/assets/images/officers/JuliaBaylon.jpg',
      },
      {
        name: 'Haki Alpay',
        position: 'Co-President of Design',
        email: 'hak7alp@gmail.com',
        picture: '/assets/images/officers/HakiAlpay.jpg',
      },
      {
        name: 'Tomoki Fukazawa',
        position: 'Co-President of Design',
        email: 'tomoki@fukazawa.dev',
        picture: '/assets/images/officers/TomokiFukazawa.jpg',
      },
      {
        name: 'Matt Wang',
        position: 'President of Teach LA',
        email: 'matt@matthewwang.me',
        picture: '/assets/images/officers/MattWang.jpg',
      },
    ],
    resources: [
      {
        type: 'facebook',
        title: 'Facebook',
        subtitle: 'facebook.com/uclaacm',
        link: 'http://facebook.com/uclaacm',
      },
      {
        type: 'twitter',
        title: 'Twitter',
        subtitle: 'twitter.com/uclaacm',
        link: 'http://twitter.com/uclaacm',
      },
      {
        type: 'github',
        title: 'Github',
        subtitle: 'github.com/uclaacm',
        link: 'http://github.com/uclaacm',
      },
      {
        type: 'website',
        title: 'Website',
        subtitle: 'acm.cs.ucla.edu',
        link: 'http://acm.cs.ucla.edu',
      },
      {
        type: 'medium',
        title: 'Medium',
        subtitle: 'tech@ucla',
        link: 'https://medium.com/techatucla',
      },
      {
        type: 'slack',
        title: 'Slack',
        subtitle: 'uclaacm.slack.com',
        link: 'http://uclaacm.slack.com',
      },
    ],
  },
  levels: [
    { startsAt: 0, rank: 'Hello, World!' },
    { startsAt: 20, rank: 'Factorial Fly' },
    { startsAt: 40, rank: 'Exponential Elephant' },
    { startsAt: 80, rank: 'Cubic Chipmunk' },
    { startsAt: 120, rank: 'Quadratic Quokka' },
    { startsAt: 180, rank: 'Linearithmic Lizard' },
    { startsAt: 240, rank: 'Linear Lemur' },
    { startsAt: 320, rank: 'Square Root Sabre-Tooth' },
    { startsAt: 400, rank: 'Logarithmic Lynx' },
    { startsAt: 500, rank: 'Constant Cheetah' },
    { startsAt: 800, rank: 'Extraterrestrial Eagle' },
    { startsAt: 1000, rank: 'Binomial Baboon' },
    { startsAt: 1300, rank: 'Scalar Scorpion' },
  ],
};
